import { defineStore } from 'pinia';
import { Tarot } from 'components/models';

export const useTarotStore = defineStore('counter', {
  state: () => ({
    tarots: <Tarot[]>[
      {
        id: '1',
        number: '0',
        name: 'The Fool',
        description: 'He inspires courage, for he understands that every day is a chance to open up new areas in your life, and with that comes a mixture of anticipation, wonder, awe and curiosity.',
        type: 'Active',
        frequency: 'Once',
        effect: 'Using this card will fully restart the session at hand, the character and player will keep full memory of everything that has happened. <br /><br /> Every item, mechanic or skill unlocked will remain with the player.',
        image_url: 'https://cdnb.artstation.com/p/assets/images/images/021/046/595/4k/arnesson-art-thomas-hugo-0-the-fool.jpg',
      },
      {
        id: '2',
        number: 'I',
        name: 'The Magician',
        description: 'Remember that you are powerful, create your inner world, and the outer will follow.',
        type: 'Active',
        frequency: '∞',
        effect: 'Player will gain the ability to enter the outer planes at will.',
        image_url: 'https://cdnb.artstation.com/p/assets/images/images/043/857/041/4k/arnesson-art-thomas-hugo-1-the-magician-4.jpg',
      },
      {
        id: '3',
        number: 'II',
        name: 'The High Priestess',
        description: 'Her appearance in a reading can signify that it is time for you to listen to your intuition rather than prioritizing your intellect and conscious mind.',
        type: 'Active',
        frequency: '1 per short rest',
        effect: 'Gain creative inspiration for 1 action outside of combat, you will receive expertise with one of the following: <br /> <ol class="tw-list-disc tw-ml-8"><li>Investigation</li><li>Insight</li><li>Arcana</li><li>Perception</li></ol>When the player already has expertise with all of the skills, the player will gain an additional +2 on one of the skills.',
        image_url: 'https://cdnb.artstation.com/p/assets/images/images/044/226/367/4k/arnesson-art-thomas-hugo-2-the-high-priestess-5.jpg?1639430517',
      },
      {
        id: '4',
        number: 'III',
        name: 'The Empress',
        description: 'The Empress is associated with fertility, expression, creativity and nurturing among many other aspects.',
        type: 'Active',
        frequency: '1 p/sr',
        effect: 'Give half of your current HP to another player.',
        image_url: 'https://cdna.artstation.com/p/assets/images/images/049/597/946/4k/arnesson-art-thomas-hugo-3-the-empress-2.jpg?1652866508',
      },
      {
        id: '5',
        number: 'IV',
        name: 'The Emperor',
        description: 'He is a symbol of the masculine principle - the paternal figure in life that gives structure, creates rules and systems, and imparts knowledge',
        type: 'Active',
        frequency: '1 p/se',
        effect: 'All hostile creatures below your own level will become passive, some even submissive. However, you are not able to damage nor kill these creatures.',
        image_url: 'https://cdna.artstation.com/p/assets/images/images/021/681/662/4k/arnesson-art-thomas-hugo-the-emperor-2.jpg?1572554989',
      },
      {
        id: '6',
        number: 'V',
        name: 'The Hierophant',
        description: "The Hierophant card suggests that it's better for you to follow social structures which are established and have their own traditions",
        type: 'Active',
        frequency: '1 p/se',
        effect: 'All hostile creatures below your own level will become passive, some even submissive. However, you are not able to damage nor kill these creatures.',
        image_url: 'https://cdnb.artstation.com/p/assets/images/images/043/856/567/4k/arnesson-art-thomas-hugo-5-hierophant-3.jpg?1638439858',
      },
      {
        id: '7',
        number: 'VI',
        name: 'The Lovers',
        description: 'The trust and the unity that the lovers have gives each of them confidence and strength, empowering the other',
        type: 'Active',
        frequency: '1 p/se',
        effect: 'All hostile creatures below your own level will become passive, some even submissive. However, you are not able to damage nor kill these creatures.',
        image_url: 'https://cdnb.artstation.com/p/assets/images/images/037/255/429/4k/arnesson-art-thomas-hugo-the-lovers-7.jpg?1619900951',
      },
      {
        id: '8',
        number: 'VII',
        name: 'The Chariot',
        description: 'The Chariot shows that you should pursue the plan with a structured and ordered approach',
        type: 'Active',
        frequency: '1 p/se',
        effect: 'All hostile creatures below your own level will become passive, some even submissive. However, you are not able to damage nor kill these creatures.',
        image_url: 'https://cdna.artstation.com/p/assets/images/images/049/598/106/4k/arnesson-art-thomas-hugo-the-chariot-23.jpg?1652866767',
      },
      {
        id: '9',
        number: 'VIII',
        name: 'Justice',
        description: "If you have been wronged, this card's appearance may bring you relief. On the other hand, if your actions caused pain to others, this card serves as a warning",
        type: 'Active',
        frequency: '1 p/se',
        effect: 'All hostile creatures below your own level will become passive, some even submissive. However, you are not able to damage nor kill these creatures.',
        image_url: 'https://cdna.artstation.com/p/assets/images/images/043/537/714/4k/arnesson-art-thomas-hugo-justice-8.jpg?1637577031',
      },
      {
        id: '10',
        number: 'IX',
        name: 'The Hermit',
        description: 'He walks through the dark night of his unconscious, guided only by the low light of the northern star, with his destination being his home, his self',
        type: 'Active',
        frequency: '1 p/se',
        effect: 'All hostile creatures below your own level will become passive, some even submissive. However, you are not able to damage nor kill these creatures.',
        image_url: 'https://cdnb.artstation.com/p/assets/images/images/034/512/623/4k/arnesson-art-thomas-hugo-the-hermit-card.jpg?1612478216',
      },
      {
        id: '11',
        number: 'X',
        name: 'The Fates - (Wheel of Fortune)',
        description: 'The same forces that govern the changing of the seasons, or the rising and setting of the sun is also the master of luck and the fate of individuals',
        type: 'Active',
        frequency: '1 p/se',
        effect: 'All hostile creatures below your own level will become passive, some even submissive. However, you are not able to damage nor kill these creatures.',
        image_url: 'https://cdnb.artstation.com/p/assets/images/images/035/269/439/4k/arnesson-art-thomas-hugo-the-fates-card-3.jpg?1614550190',
      },
      {
        id: '12',
        number: 'XI',
        name: 'Strength',
        description: 'Your resilience will greatly aid you, and your fearlessness means that you should have no issues speaking your mind',
        type: 'Active',
        frequency: '1 p/se',
        effect: 'All hostile creatures below your own level will become passive, some even submissive. However, you are not able to damage nor kill these creatures.',
        image_url: 'https://cdnb.artstation.com/p/assets/images/images/049/605/087/4k/arnesson-art-thomas-hugo-strength-11.jpg?1652880082',
      },
      {
        id: '13',
        number: 'XII',
        name: 'The Hanged Man',
        description: 'The Hanged Man card reflects a particular need to suspend certain action. As a result, this might indicate a certain period of indecision',
        type: 'Active',
        frequency: '1 p/se',
        effect: 'All hostile creatures below your own level will become passive, some even submissive. However, you are not able to damage nor kill these creatures.',
        image_url: 'https://cdnb.artstation.com/p/assets/images/images/037/880/121/4k/arnesson-art-thomas-hugo-the-hanged-man-11.jpg?1621545385',
      },
      {
        id: '14',
        number: 'XIII',
        name: 'Death',
        description: 'The Death card signals that one major phase in your life is ending, and a new one is going to start',
        type: 'Active',
        frequency: '1 p/se',
        effect: 'All hostile creatures below your own level will become passive, some even submissive. However, you are not able to damage nor kill these creatures.',
        image_url: 'https://cdna.artstation.com/p/assets/images/images/038/213/806/4k/arnesson-art-thomas-hugo-death-4.jpg?1622490081',
      },
      {
        id: '15',
        number: 'XIV',
        name: 'Temperance',
        description: 'The Temperance tarot card suggests moderation and balance, coupled with a lot of patience',
        type: 'Active',
        frequency: '1 p/se',
        effect: 'All hostile creatures below your own level will become passive, some even submissive. However, you are not able to damage nor kill these creatures.',
        image_url: 'https://cdna.artstation.com/p/assets/images/images/049/582/172/4k/arnesson-art-thomas-hugo-14-temperance-15-flattened.jpg?1652820112',
      },
      {
        id: '16',
        number: 'XV',
        name: 'The Devil',
        description: 'Addiction to substances or material pleasures can also be the reason for your feelings of powerlessness and entrapment',
        type: 'Active',
        frequency: '1 p/se',
        effect: 'All hostile creatures below your own level will become passive, some even submissive. However, you are not able to damage nor kill these creatures.',
        image_url: 'https://cdna.artstation.com/p/assets/images/images/039/399/100/4k/arnesson-art-thomas-hugo-15-the-devil-10.jpg?1625777235',
      },
      {
        id: '17',
        number: 'XVI',
        name: 'The Lightning - (The Tower)',
        description: 'The old ways are no longer useful, and you must find another set of beliefs, values and processes to take their place',
        type: 'Active',
        frequency: '1 p/se',
        effect: 'All hostile creatures below your own level will become passive, some even submissive. However, you are not able to damage nor kill these creatures.',
        image_url: 'https://cdnb.artstation.com/p/assets/images/images/044/067/189/4k/arnesson-art-thomas-hugo-2-the-lightning-7.jpg?1638997194',
      },
      {
        id: '18',
        number: 'XVII',
        name: 'The Star',
        description: 'To see this card is a message to have faith, for the universe will bless you and bring forth all that you need',
        type: 'Active',
        frequency: '1 p/se',
        effect: 'All hostile creatures below your own level will become passive, some even submissive. However, you are not able to damage nor kill these creatures.',
        image_url: 'https://cdnb.artstation.com/p/assets/images/images/043/808/065/4k/arnesson-art-thomas-hugo-15-the-star-4.jpg?1638307786',
      },
      {
        id: '19',
        number: 'XVIII',
        name: 'The Moon',
        description: "The moon's light can bring you clarity and understanding and you should allow your intuition to guide you through this darkness",
        type: 'Active',
        frequency: '1 p/se',
        effect: 'All hostile creatures below your own level will become passive, some even submissive. However, you are not able to damage nor kill these creatures.',
        image_url: 'https://cdna.artstation.com/p/assets/images/images/044/226/348/4k/arnesson-art-thomas-hugo-18-the-moon-6.jpg?1639430481',
      },
      {
        id: '20',
        number: 'XIX',
        name: 'The Sun',
        description: 'The card shows that you have a significant sense of deserved confidence right now',
        type: 'Active',
        frequency: '1 p/se',
        effect: 'All hostile creatures below your own level will become passive, some even submissive. However, you are not able to damage nor kill these creatures.',
        image_url: 'https://cdnb.artstation.com/p/assets/images/images/042/247/691/4k/arnesson-art-thomas-hugo-19-the-sun-11.jpg?1633984172',
      },
      {
        id: '21',
        number: 'XX',
        name: 'The Judgement',
        description: 'To see this card can also indicate that you are in a period of awakening, brought on by the act of self-reflection',
        type: 'Active',
        frequency: '1 p/se',
        effect: 'All hostile creatures below your own level will become passive, some even submissive. However, you are not able to damage nor kill these creatures.',
        image_url: 'https://cdnb.artstation.com/p/assets/images/images/044/162/957/4k/arnesson-art-thomas-hugo-20-judgement-16.jpg?1639261057',
      },
      {
        id: '22',
        number: 'XXI',
        name: 'The World',
        description: 'To encounter the World in your cards is to encounter a great unity and wholeness',
        type: 'Active',
        frequency: '1 p/se',
        effect: 'All hostile creatures below your own level will become passive, some even submissive. However, you are not able to damage nor kill these creatures.',
        image_url: 'https://cdna.artstation.com/p/assets/images/images/051/342/890/4k/arnesson-art-thomas-hugo-the-world-v10.jpg?1657052945',
      },
    ],
    current: <Tarot>{}
  }),
  getters: {
    all: (state) => state.tarots,
  },
  actions: {
    setCurrent(id: string | string[]) {
      const index = this.tarots.findIndex((tarot) => tarot.id == id);
      this.current = this.tarots[index] ?? {};
    },
  },
});
